apiVersion: apps/v1
kind: Deployment
metadata:
  name: tofu-k8s-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tofu-k8s-operator
  template:
    metadata:
      labels:
        app: tofu-k8s-operator
    spec:
      serviceAccountName: tofu-k8s-operator
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-bind-address={{ .Values.metricsBindAddress }}
            - --health-probe-bind-address={{ .Values.healthProbeBindAddress }}
            {{- if .Values.leaderElect }}
            - --leader-elect
            {{- end }}
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health
